name: webkitgtk # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '6.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Web content engine for GTK # 79 char long summary
description: |
  Content snap for Webkitgtk-6.0+

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  webkitgtk:
    interface: content
    read:
      - /

parts:
  webkitgtk:
    plugin: nil
    stage-snaps: [ webkitgtk-sdk/latest/edge ]
    prime:
      - usr/bin/WebKitWebDriver
      - usr/bin/bwrap
      - usr/share/gir-1.0/*
      - usr/share/locale/*
      - usr/lib/libjavascriptcoregtk*
      - usr/lib/webkitgtk-6.0/*
      - usr/lib/libwebkitgtk*
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/lapack/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libv4l/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libv4lconvert0/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/mfx/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/perl5
      - usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/vdpau/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libabsl*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libaom*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libass*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libavc*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libavf*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libavif*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libavu*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libb*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libchroma*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libcodec*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libdav*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libflite*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgav*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgfortran*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgme*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgsm*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstadaptive*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstbad*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstcodec*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstin*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstis*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstmpeg*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstplay*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstctp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstt*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstu*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstva*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstwayland*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstweb*
      - usr/lib/$CRAFT_ARCH_TRIPLET/liblil*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libmfx*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libmysofa*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libnorm*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libnuma*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libOp*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libopenmpt*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpgm*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpixman*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpocket*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpsl*
      - usr/lib/$CRAFT_ARCH_TRIPLET/librabbitmq*
      - usr/lib/$CRAFT_ARCH_TRIPLET/librsvg*
      - usr/lib/$CRAFT_ARCH_TRIPLET/librubb*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libserd*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libshine*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsodium*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsnappy*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsord*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsoup*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsoxr*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsphinx*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsr*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libssh*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libsw*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libudfread*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libva*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libvdpau*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libwpe*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libWPE*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libx264*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libx265*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libxvid*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libyuv*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libzimg*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libzmq*
      - usr/lib/$CRAFT_ARCH_TRIPLET/libzvb*
      - usr/share/alsa
      - usr/share/gettext
      - usr/share/gir-1.0
      - usr/share/glvnd
      - usr/share/gstreamer-1.0
      - usr/share/iso-codes
      - usr/share/libmysofa
      - usr/share/locale
      - usr/share/mfx:amd64
      - usr/share/mime
      - usr/share/perl5 

