name: webkitgtk # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '6.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Web content engine for GTK # 79 char long summary
description: |
  Content snap for Webkitgtk-6.0+

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  webkitgtk:
    interface: content
    read:
      - /

parts:
  webkitgtk:
    plugin: nil
    stage-snaps: [ webkitgtk-sdk/latest/edge ]
    prime:
      - usr/bin/WebKitWebDriver
      - usr/share/gir-1.0/*
      - usr/share/locale/*
      - usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/*
      - usr/lib/libjavascriptcoregtk*
      - usr/lib/webkitgtk-6.0/*
      - usr/lib/libwebkitgtk*
  deps:
    plugin: nil
    stage-packages:
      - bubblewrap
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - libabsl20210324
      - libaom3
      - libatomic1
      - libavif13
      - libdav1d5
      - libenchant-2-2
      - libepoxy0
      - libgles2
      - libglx0
      - libgav1-0
      - libglu1-mesa
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer1.0-0
      #- libgtk-4-1
      #- libharfbuzz-icu0
      - libhyphen0
      - liblcms2-2
      - libmanette-0.2-0
      - libnghttp2-14
      - libopengl0
      - libopenjp2-7
      - libsecret-1-0
      - libseccomp2
      - libtasn1-6
      - libwebp7
      - libwebpdemux2
      - libwoff1  
      - libwpe-1.0-1
      - libwpebackend-fdo-1.0-1
      - libxcomposite1
      - libxslt1.1
      - libyuv0
      - libsoup-3.0-0
      - libsystemd0
      - xdg-dbus-proxy
    override-prime: |
      craftctl default
      cd $CRAFT_PRIME
      rm -rf usr/lib/*/caca
      rm -rf usr/lib/*/libharfbuzz*



